


server {
    listen        one.example.com;
    server_name   one.example.com  www.one.example.com;
    error_page  404  /404.html;

    location / {
        client_max_body_size       10m;
    }

    location /old_stuff/ {
        rewrite   ^/old_stuff/(.*)$  /new_stuff/$1  permanent;
    }

    location /download/ {

        valid_referers  none  blocked  server_names  *.example.com;

        if ($invalid_referer) {
            #rewrite   ^/   http://www.example.com/;
            return   403;
        }

        #rewrite_log  on;

        # rewrite /download/*/mp3/*.any_ext to /download/*/mp3/*.mp3
        rewrite ^/(download/.*)/mp3/(.*)\..*$
                /$1/mp3/$2.mp3                   break;

        root         /spool/www;
        #autoindex    on;
        access_log   /var/log/nginx-download.access_log  download;
    }

    location ~* \.(jpg|jpeg|gif)$ {
        root         /spool/www;
        access_log   off;
        expires      30d;
    }
}